<html>
<head>
    <meta charset="UTF-8">
    <title>Buttons</title>
    <?php include './include/head.html'?>
</head>
<body>
    <div class="zm" style="width: auto; min-width: 100px; max-width: 700px; height: 500px; position: relative; margin: 50px auto; align-content: center">
        <button class="waves-effect waves-light zdk-btn zm">button</button>
        <button class="waves-effect waves-light zdk-btn zm">button</button>
        <button class="waves-effect waves-light zdk-btn zm"><i class="material-icons zdk-left zm">cloud</i>button</button>
        <button class="waves-effect waves-light zdk-btn zm"><i class="material-icons zdk-right zm">cloud</i>button</button>
        <div data-materialize-init="true" class="zdk-fixed-action-btn zdk-horizontal zm" style="top: 45px; right: 24px;">
            <a class="zdk-btn-floating zdk-btn-large zdk-red">
                <i class="material-icons">menu</i>
            </a>
            <ul>
                <li><a class="zdk-btn-floating zdk-red zm"><i class="material-icons zm">insert_chart</i></a></li>
                <li><a class="zdk-btn-floating zdk-yellow zdk-darken-1 zm"><i class="material-icons zm">format_quote</i></a></li>
                <li><a class="zdk-btn-floating zdk-green zm"><i class="material-icons zm">publish</i></a></li>
                <li><a class="zdk-btn-floating zdk-blue zm"><i class="material-icons zm">attach_file</i></a></li>
            </ul>
        </div>
        <div data-materialize-init="true" class="zdk-fixed-action-btn zdk-horizontal zdk-click-to-toggle zm xinchao" style="top: 125px; right: 24px;">
            <a class="zdk-btn-floating zdk-btn-large zdk-red zm">
                <i class="material-icons zm">menu</i>
            </a>
            <ul>
                <li><a class="zdk-btn-floating zdk-red zm"><i class="material-icons zm">insert_chart</i></a></li>
                <li><a class="zdk-btn-floating zdk-yellow zdk-darken-1 zm"><i class="material-icons zm">format_quote</i></a></li>
                <li><a class="zdk-btn-floating zdk-green zm"><i class="material-icons zm">publish</i></a></li>
                <li><a class="zdk-btn-floating zdk-blue zm"><i class="material-icons zm">attach_file</i></a></li>
            </ul>
        </div>
        <a class="add-wave-effect-btn zdk-btn-floating zdk-btn-large waves-effect waves-light zdk-red zm"><i class="material-icons">add</i></a>
    </div>
    <div data-test-1="1" class="xinchao cac ban data den" data-test-2="{my_%real{ly:s#tra`n[ge_i]d_n^@a|me>}"></div>
    <div class="test-container" style="position: absolute;top: 0;">
        <div class="mini-container">
            <button class="test">sdfsdfsdfs</button>
        </div>
    </div>
</body>
</html>