<html>
<head>
    <meta charset="UTF-8">
    <title>Cards</title>
    <?php include './include/head.html'?>
</head>
<body>
    <div class="zdk-container zdk">
        <div class="zdk-row">
            <div class="zdk-col zdk-s12 zdk-m9 zdk-l10">
                <div class="zdk-row">
                    <div class="zdk-col zdk-s12 zdk-m6">
                        <div class="zdk-card zdk-blue-grey zdk-darken-1">
                            <div class="zdk-card-content zdk-white-text">
                                <span class="zdk-card-title zdk">Card Title</span>
                                <p>I am a very simple card. I am good at containing small bits of information.
                                    I am convenient because I require little markup to use effectively.</p>
                            </div>
                            <div class="zdk-card-action">
                                <a href="#" class="zdk-card-link zdk">This is a link</a>
                                <a href="#" class="zdk-card-link zdk">This is a link</a>
                            </div>
                        </div>
                    </div>
                    <div class="zdk-col zdk-s12 zdk-m7">
                        <div class="zdk-card">
                            <div class="zdk-card-image">
                                <img src="../images/sample-1.jpg" class="zdk">
                                <span class="zdk-card-title zdk" >Card Title</span>
                            </div>
                            <div class="zdk-card-content">
                                <p>I am a very simple card. I am good at containing small bits of information.
                                    I am convenient because I require little markup to use effectively.</p>
                            </div>
                            <div class="zdk-card-action">
                                <a href="#" class="zdk-card-link zdk">This is a link</a>
                            </div>
                        </div>
                    </div>
                    <div class="zdk-col zdk-s12 zdk-m7">
                        <h2 class="zdk-header zdk">Card Reveal</h2>
                        <div data-materialize-init="true" class="zdk-card zdk-sticky-action">
                            <div class="zdk-card-image waves-effect waves-block waves-light">
                                <img class="zdk-activator zdk" src="../images/office.jpg">
                            </div>
                            <div class="zdk-card-content">
                                <span class="zdk-card-title zdk-activator zdk-grey-text zdk-text-darken-4 zdk">Card Title<i class="zdk-material-icons zdk-right zdk">more_vert</i></span>
                                <p><a href="#" class="zdk">This is a link</a></p>
                            </div>
                            <div class="zdk-card-reveal">
                                <span class="zdk-card-title zdk-grey-text zdk-text-darken-4">Card Title<i class="zdk-material-icons zdk-right">close</i></span>
                                <p>Here is some more information about this product that is only revealed once clicked on.</p>
                            </div>
                            <div class="zdk-card-action">
                                <a href="#" class="zdk-card-link zdk">This is a link</a>
                                <a href="#" class="zdk-card-link zdk">This is a link</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>