<html>
<head>
    <meta charset="UTF-8">
    <title>Chips</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zdk-container zdk" style="position: relative; top: 20px;">
    <div class="zdk-row">
        <div class="zdk-col zdk-s12 zdk-m9 zdk-l10">
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m6">
                    <div class="zdk-chip">
                        <img src="../images/yuna.jpg" class="zdk" alt="Contact Person">
                        Jane Doe
                    </div>
                    <div class="zdk-chip">
                        Tag
                        <i class="zdk-material-icons zdk-close zdk">close</i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>