<html>
<head>
    <meta charset="UTF-8">
    <title>Collections</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zdk-container zdk" style="position: relative; top: 20px;">
    <div class="zdk-row">
        <div class="zdk-col zdk-s12 zdk-m9 zdk-l10">
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <ul class="zdk-collection zdk">
                        <li class="zdk-collection-item">Alvin</li>
                        <li class="zdk-collection-item">Alvin</li>
                        <li class="zdk-collection-item">Alvin</li>
                        <li class="zdk-collection-item">Alvin</li>
                    </ul>
                </div>
            </div>
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <div class="zdk-collection zdk">
                        <a href="#!" class="zdk-collection-item zdk">Alvin</a>
                        <a href="#!" class="zdk-collection-item zdk-active zdk">Alvin</a>
                        <a href="#!" class="zdk-collection-item zdk">Alvin</a>
                        <a href="#!" class="zdk-collection-item zdk">Alvin</a>
                    </div>
                </div>
            </div>
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <ul class="zdk-collection zdk-with-header zdk">
                        <li class="zdk-collection-header"><h4>First Names</h4></li>
                        <li class="zdk-collection-item">Alvin</li>
                        <li class="zdk-collection-item">Alvin</li>
                        <li class="zdk-collection-item">Alvin</li>
                        <li class="zdk-collection-item">Alvin</li>
                    </ul>
                </div>
            </div>
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <ul class="zdk-collection zdk-with-header zdk">
                        <li class="zdk-collection-header"><h4>First Names</h4></li>
                        <li class="zdk-collection-item"><div>Alvin<a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">send</i></a></div></li>
                        <li class="zdk-collection-item"><div>Alvin<a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">send</i></a></div></li>
                        <li class="zdk-collection-item"><div>Alvin<a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">send</i></a></div></li>
                        <li class="zdk-collection-item"><div>Alvin<a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">send</i></a></div></li>
                    </ul>
                </div>
            </div>
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <ul class="zdk-collection zdk-with-header zdk">
                        <li class="zdk-collection-header"><h4>First Names</h4></li>
                        <li class="zdk-collection-item"><div>Alvin<a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">send</i></a></div></li>
                        <li class="zdk-collection-item"><div>Alvin<a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">send</i></a></div></li>
                        <li class="zdk-collection-item"><div>Alvin<a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">send</i></a></div></li>
                        <li class="zdk-collection-item"><div>Alvin<a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">send</i></a></div></li>
                    </ul>
                </div>
            </div>
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <ul class="zdk-collection zdk">
                        <li class="zdk-collection-item zdk-avatar">
                            <img src="../images/yuna.jpg" alt="" class="zdk-circle zdk">
                            <span class="zdk-title zdk">Title</span>
                            <p>First Line <br>
                                Second Line
                            </p>
                            <a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">grade</i></a>
                        </li>
                        <li class="zdk-collection-item zdk-avatar">
                            <i class="zdk-material-icons zdk-circle zdk">folder</i>
                            <span class="zdk-title zdk">Title</span>
                            <p>First Line <br>
                                Second Line
                            </p>
                            <a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">grade</i></a>
                        </li>
                        <li class="zdk-collection-item zdk-avatar">
                            <i class="zdk-material-icons zdk-circle zdk-green zdk">insert_chart</i>
                            <span class="zdk-title zdk">Title</span>
                            <p>First Line <br>
                                Second Line
                            </p>
                            <a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">grade</i></a>
                        </li>
                        <li class="zdk-collection-item zdk-avatar">
                            <i class="zdk-material-icons zdk-circle zdk-red zdk">play_arrow</i>
                            <span class="zdk-title zdk">Title</span>
                            <p>First Line <br>
                                Second Line
                            </p>
                            <a href="#!" class="zdk-secondary-content zdk"><i class="zdk-material-icons zdk">grade</i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>