<html>
<head>
    <meta charset="UTF-8">
    <title>Dialogs</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zdk-container zdk" style="position: relative; top: 20px;">
    <div class="zdk-row">
        <div class="zdk-col zdk-s12 zdk-m9 zdk-l10">
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m6">
                    <a class="zdk-btn zdk" onclick="Zendkofy.toast('I am a toast', 2000)">Toast!</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>