<html>
<head>
    <meta charset="UTF-8">
    <title>Chips</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zdk-container zdk" style="position: relative; top: 20px;">
    <div class="zdk-row">
        <div class="zdk-col zdk-s12 zdk-m9 zdk-l10">
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m6">
                    <!-- Dropdown Trigger -->
                    <a data-materialize-init=true class='zdk-dropdown-button zdk-btn zdk' href='#' data-activates='dropdown1'>Drop Me!</a>

                    <!-- Dropdown Structure -->
                    <ul id='dropdown1' class='zdk-dropdown-content'>
                        <li><a href="#!" class="zdk">one</a></li>
                        <li class="zdk-divider zdk" ></li>
                        <li><a href="#!" class="zdk">two</a></li>
                        <li class="zdk-divider zdk" ></li>
                        <li><a href="#!" class="zdk">three</a></li>
                        <li class="zdk-divider zdk" ></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>