<html>
<head>
    <meta charset="UTF-8">
    <title>Media</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zdk-container zdk" style="position: relative; top: 20px;">
    <div class="zdk-row">
        <div class="zdk-col zdk-s12 zdk-m9 zdk-l10">
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m6">
                    <img data-materialize-init="true" class="zdk-materialboxed zdk" width="300" src="../images/sample-1.jpg">
                    <img data-materialize-init="true" class="zdk-materialboxed zdk" data-caption="A picture of some deer and tons of trees" width="250" src="http://th01.deviantart.net/fs70/PRE/i/2013/126/1/e/nature_portrait_by_pw_fotografie-d63tx0n.jpg">
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>