<html>
<head>
    <meta charset="UTF-8">
    <title>Media</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zdk-container zdk" style="position: relative; top: 20px;">
    <div class="zdk-row">
        <div class="zdk-col zdk-s12 zdk-m9 zdk-l10">
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m6">
                    <img data-materialize-init="true" class="zdk-materialboxed zdk" width="300" src="../images/sample-1.jpg">
                    <img data-materialize-init="true" class="zdk-materialboxed zdk" data-caption="A picture of some deer and tons of trees" width="250" src="http://th01.deviantart.net/fs70/PRE/i/2013/126/1/e/nature_portrait_by_pw_fotografie-d63tx0n.jpg">
                </div>
            </div>
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <div data-materialize-init="true" class="zdk-slider">
                        <ul class="zdk-slides zdk">
                            <li>
                                <img src="http://lorempixel.com/580/250/nature/1" class="zdk"/> <!-- random image -->
                                <div class="zdk-caption zdk-center-align">
                                    <h3 class="zdk">This is our big Tagline!</h3>
                                    <h5 class="zdk-light zdk-grey-text zdk-text-lighten-3 zdk">Here's our small slogan.</h5>
                                </div>
                            </li>
                            <li>
                                <img src="http://lorempixel.com/580/250/nature/2" class="zdk"/> <!-- random image -->
                                <div class="zdk-caption zdk-left-align">
                                    <h3 class="zdk">Left Aligned Caption</h3>
                                    <h5 class="zdk-light zdk-grey-text zdk-text-lighten-3 zdk">Here's our small slogan.</h5>
                                </div>
                            </li>
                            <li>
                                <img src="http://lorempixel.com/580/250/nature/3" class="zdk"/> <!-- random image -->
                                <div class="zdk-caption zdk-right-align">
                                    <h3 class="zdk">Right Aligned Caption</h3>
                                    <h5 class="zdk-light zdk-grey-text zdk-text-lighten-3 zdk">Here's our small slogan.</h5>
                                </div>
                            </li>
                            <li>
                                <img src="http://lorempixel.com/580/250/nature/4" class="zdk"/> <!-- random image -->
                                <div class="zdk-caption zdk-center-align">
                                    <h3 class="zdk">This is our big Tagline!</h3>
                                    <h5 class="zdk-light zdk-grey-text zdk-text-lighten-3 zdk">Here's our small slogan.</h5>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <div data-materialize-init="true" class="zdk-carousel">
                        <a class="zdk-carousel-item zdk" href="#one!"><img class="zdk" src="http://lorempixel.com/250/250/nature/1"></a>
                        <a class="zdk-carousel-item zdk" href="#two!"><img class="zdk" src="http://lorempixel.com/250/250/nature/2"></a>
                        <a class="zdk-carousel-item zdk" href="#three!"><img class="zdk" src="http://lorempixel.com/250/250/nature/3"></a>
                        <a class="zdk-carousel-item zdk" href="#four!"><img class="zdk" src="http://lorempixel.com/250/250/nature/4"></a>
                        <a class="zdk-carousel-item zdk" href="#five!"><img class="zdk" src="http://lorempixel.com/250/250/nature/5"></a>
                    </div>
                </div>
            </div>
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <div data-materialize-init="true" class="zdk-carousel zdk-carousel-slider">
                        <a class="zdk-carousel-item zdk" href="#one!"><img class="zdk" src="http://lorempixel.com/800/400/food/1"></a>
                        <a class="zdk-carousel-item zdk" href="#two!"><img class="zdk" src="http://lorempixel.com/800/400/food/2"></a>
                        <a class="zdk-carousel-item zdk" href="#three!"><img class="zdk" src="http://lorempixel.com/800/400/food/3"></a>
                        <a class="zdk-carousel-item zdk" href="#four!"><img class="zdk" src="http://lorempixel.com/800/400/food/4"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>