<html>
<head>
    <meta charset="UTF-8">
    <title>Navbar</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zdk-container zm" style="position: relative; top: 20px;">
    <div class="zdk-row">
        <div class="zdk-col zdk-s12 zdk-m9 zdk-l10">
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <nav class="zm">
                        <div class="zdk-nav-wrapper">
                            <div class="zdk-col zdk-s12 zdk-m12">
                                <a href="#" class="zdk-brand-logo zm">Logo</a>
                                <ul id="nav-mobile" class="zdk-right zdk-hide-on-med-and-down zm">
                                    <li><a href="sass.html" class="zm">Sass</a></li>
                                    <li><a href="badges.html" class="zm">Components</a></li>
                                    <li><a href="collapsible.html" class="zm">JavaScript</a></li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <nav class="zm">
                        <div class="zdk-nav-wrapper">
                            <div class="zdk-col zdk-s12 zdk-m12">
                                <a href="#" class="zdk-brand-logo zdk-right zm">Logo</a>
                                <ul id="nav-mobile" class="zdk-left zdk-hide-on-med-and-down zm">
                                    <li><a href="sass.html" class="zm">Sass</a></li>
                                    <li><a href="badges.html" class="zm">Components</a></li>
                                    <li><a href="collapsible.html" class="zm">JavaScript</a></li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m12">
                    <!-- Dropdown Structure -->
                    <ul id="dropdown1" class="zdk-dropdown-content zm">
                        <li><a href="#!" class="zm">one</a></li>
                        <li><a href="#!" class="zm">two</a></li>
                        <li class="zdk-divider"></li>
                        <li><a href="#!" class="zm">three</a></li>
                    </ul>
                    <nav class="zm">
                        <div class="zdk-nav-wrapper">
                            <div class="zdk-col zdk-s12 zdk-m12">
                                <a href="#!" class="zdk-brand-logo zm">Logo</a>
                                <ul class="navbar-link zdk-right zdk-hide-on-med-and-down zm">
                                    <li><a href="sass.html" class="zm">Sass</a></li>
                                    <li><a href="badges.html" class="zm">Components</a></li>
                                    <!-- Dropdown Trigger -->
                                    <li><a data-materialize-init="true" class="zdk-dropdown-button zm" href="#!" data-activates="dropdown1">Dropdown<i class="zdk-material-icons zdk-right zm">arrow_drop_down</i></a></li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>