<html>
<head>
    <meta charset="UTF-8">
    <title>Pagination</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zdk-container zdk" style="position: relative; top: 20px;">
    <div class="zdk-row">
        <div class="zdk-col zdk-s12 zdk-m9 zdk-l10">
            <div class="zdk-row">
                <div class="zdk-col zdk-s12 zdk-m6">
                    <ul class="zdk-pagination zdk">
                        <li class="zdk-disabled"><a class="zdk" href="#!"><i class="zdk-material-icons zdk">chevron_left</i></a></li>
                        <li class="zdk-active"><a class="zdk"  href="#!">1</a></li>
                        <li class="waves-effect"><a class="zdk"  href="#!">2</a></li>
                        <li class="waves-effect"><a class="zdk"  href="#!">3</a></li>
                        <li class="waves-effect"><a class="zdk"  href="#!">4</a></li>
                        <li class="waves-effect"><a class="zdk"  href="#!">5</a></li>
                        <li class="waves-effect"><a class="zdk"  href="#!"><i class="zdk-material-icons zdk">chevron_right</i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>