<html>
<head>
    <meta charset="UTF-8">
    <title>Scrollspy</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zdk-container zdk" style="position: relative; top: 20px;">
    <div class="zdk-row">
        <div class="zdk-col zdk-s12 zdk-m9 zdk-l10">
            <div id="introduction" class="zdk-section zdk-scrollspy">
                <p>Content </p>
            </div>

            <div id="structure" class="zdk-section zdk-scrollspy">
                <p>Content </p>
            </div>

            <div id="initialization" class="zdk-section zdk-scrollspy">
                <p>Content </p>
            </div>
        </div>
        <div class="zdk-col zdk-hide-on-small-only zdk-m3 zdk-l2">
            <ul class="zdk-section zdk-table-of-contents">
                <li><a class="zdk" href="#introduction">Introduction</a></li>
                <li><a class="zdk" href="#structure">Structure</a></li>
                <li><a class="zdk" href="#initialization">Intialization</a></li>
            </ul>
        </div>
        <script type="text/javascript">
            require(['jquery', 'material/scrollspy'], function ($) {
                $(document).ready(function(){
                    $('.zdk-scrollspy').scrollSpy();
                });
            })
        </script>
    </div>
</div>
</body>
</html>