<html>
<head>
    <meta charset="UTF-8">
    <title>Breadcrumbs</title>
    <?php include './include/head.html'?>
</head>
<body>
<div style="width: auto; min-width: 100px; max-width: 700px; height: 500px; position: relative; margin: 50px auto; align-content: center">
    <div class="zm-row">
        <nav class="zm">
            <div class="zm-nav-wrapper">
                <div class="zm-col zm-s12">
                    <a href="#!" class="zm-breadcrumb zm">First</a>
                    <a href="#!" class="zm-breadcrumb zm">Second</a>
                    <a href="#!" class="zm-breadcrumb zm">Third</a>
                </div>
            </div>
        </nav>
    </div>
</div>
</body>
</html>