<html>
<head>
    <meta charset="UTF-8">
    <title>Cards</title>
    <?php include './include/head.html'?>
</head>
<body>
    <div class="zm-container zm">
        <div class="zm-row">
            <div class="zm-col zm-s12 zm-m9 zm-l10">
                <div class="zm-row">
                    <!--        <div class="zm-col zm-s12 zm-m6">-->
                    <!--            <div class="zm-card zm-blue-grey zm-darken-1">-->
                    <!--                <div class="zm-card-content zm-white-text">-->
                    <!--                    <span class="zm-card-title zm">Card Title</span>-->
                    <!--                    <p>I am a very simple card. I am good at containing small bits of information.-->
                    <!--                        I am convenient because I require little markup to use effectively.</p>-->
                    <!--                </div>-->
                    <!--                <div class="zm-card-action">-->
                    <!--                    <a href="#" class="zm-card-link zm">This is a link</a>-->
                    <!--                    <a href="#" class="zm-card-link zm">This is a link</a>-->
                    <!--                </div>-->
                    <!--            </div>-->
                    <!--        </div>-->
                    <!--        <div class="zm-col zm-s12 zm-m7">-->
                    <!--            <div class="zm-card">-->
                    <!--                <div class="zm-card-image">-->
                    <!--                    <img src="../images/sample-1.jpg" class="zm">-->
                    <!--                    <span class="zm-card-title zm" >Card Title</span>-->
                    <!--                </div>-->
                    <!--                <div class="zm-card-content">-->
                    <!--                    <p>I am a very simple card. I am good at containing small bits of information.-->
                    <!--                        I am convenient because I require little markup to use effectively.</p>-->
                    <!--                </div>-->
                    <!--                <div class="zm-card-action">-->
                    <!--                    <a href="#" class="zm-card-link zm">This is a link</a>-->
                    <!--                </div>-->
                    <!--            </div>-->
                    <!--        </div>-->
                    <div class="zm-col zm-s12 zm-m7">
                        <h2 class="zm-header zm">Card Reveal</h2>
                        <div data-materialize-init="true" class="zm-card">
                            <div class="zm-card-image waves-effect waves-block waves-light">
                                <img class="zm-activator zm" src="../images/office.jpg">
                            </div>
                            <div class="zm-card-content">
                                <span class="zm-card-title zm-activator zm-grey-text zm-text-darken-4 zm">Card Title<i class="zm-material-icons zm-right zm">more_vert</i></span>
                                <p><a href="#" class="zm">This is a link</a></p>
                            </div>
                            <div class="zm-card-reveal">
                                <span class="zm-card-title zm-grey-text zm-text-darken-4">Card Title<i class="zm-material-icons zm-right">close</i></span>
                                <p>Here is some more information about this product that is only revealed once clicked on.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>