<html>
<head>
    <meta charset="UTF-8">
    <title>Chips</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zm-container zm" style="position: relative; top: 20px;">
    <div class="zm-row">
        <div class="zm-col zm-s12 zm-m9 zm-l10">
            <div class="zm-row">
                <div class="zm-col zm-s12 zm-m6">
                    <div class="zm-chip">
                        <img src="../images/yuna.jpg" class="zm" alt="Contact Person">
                        Jane Doe
                    </div>
                    <div class="zm-chip">
                        Tag
                        <i class="zm-material-icons zm-close zm">close</i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>