<html>
<head>
    <meta charset="UTF-8">
    <title>Collections</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zm-container zm" style="position: relative; top: 20px;">
    <div class="zm-row">
        <div class="zm-col zm-s12 zm-m9 zm-l10">
            <div class="zm-row">
                <div class="zm-col zm-s12 zm-m12">
                    <ul class="zm-collection zm">
                        <li class="zm-collection-item">Alvin</li>
                        <li class="zm-collection-item">Alvin</li>
                        <li class="zm-collection-item">Alvin</li>
                        <li class="zm-collection-item">Alvin</li>
                    </ul>
                </div>
            </div>
            <div class="zm-row">
                <div class="zm-col zm-s12 zm-m12">
                    <div class="zm-collection zm">
                        <a href="#!" class="zm-collection-item zm">Alvin</a>
                        <a href="#!" class="zm-collection-item zm-active zm">Alvin</a>
                        <a href="#!" class="zm-collection-item zm">Alvin</a>
                        <a href="#!" class="zm-collection-item zm">Alvin</a>
                    </div>
                </div>
            </div>
            <div class="zm-row">
                <div class="zm-col zm-s12 zm-m12">
                    <ul class="zm-collection zm-with-header zm">
                        <li class="zm-collection-header"><h4>First Names</h4></li>
                        <li class="zm-collection-item">Alvin</li>
                        <li class="zm-collection-item">Alvin</li>
                        <li class="zm-collection-item">Alvin</li>
                        <li class="zm-collection-item">Alvin</li>
                    </ul>
                </div>
            </div>
            <div class="zm-row">
                <div class="zm-col zm-s12 zm-m12">
                    <ul class="zm-collection zm-with-header zm">
                        <li class="zm-collection-header"><h4>First Names</h4></li>
                        <li class="zm-collection-item"><div>Alvin<a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">send</i></a></div></li>
                        <li class="zm-collection-item"><div>Alvin<a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">send</i></a></div></li>
                        <li class="zm-collection-item"><div>Alvin<a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">send</i></a></div></li>
                        <li class="zm-collection-item"><div>Alvin<a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">send</i></a></div></li>
                    </ul>
                </div>
            </div>
            <div class="zm-row">
                <div class="zm-col zm-s12 zm-m12">
                    <ul class="zm-collection zm-with-header zm">
                        <li class="zm-collection-header"><h4>First Names</h4></li>
                        <li class="zm-collection-item"><div>Alvin<a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">send</i></a></div></li>
                        <li class="zm-collection-item"><div>Alvin<a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">send</i></a></div></li>
                        <li class="zm-collection-item"><div>Alvin<a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">send</i></a></div></li>
                        <li class="zm-collection-item"><div>Alvin<a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">send</i></a></div></li>
                    </ul>
                </div>
            </div>
            <div class="zm-row">
                <div class="zm-col zm-s12 zm-m12">
                    <ul class="zm-collection zm">
                        <li class="zm-collection-item zm-avatar">
                            <img src="../images/yuna.jpg" alt="" class="zm-circle zm">
                            <span class="zm-title zm">Title</span>
                            <p>First Line <br>
                                Second Line
                            </p>
                            <a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">grade</i></a>
                        </li>
                        <li class="zm-collection-item zm-avatar">
                            <i class="zm-material-icons zm-circle zm">folder</i>
                            <span class="zm-title zm">Title</span>
                            <p>First Line <br>
                                Second Line
                            </p>
                            <a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">grade</i></a>
                        </li>
                        <li class="zm-collection-item zm-avatar">
                            <i class="zm-material-icons zm-circle zm-green zm">insert_chart</i>
                            <span class="zm-title zm">Title</span>
                            <p>First Line <br>
                                Second Line
                            </p>
                            <a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">grade</i></a>
                        </li>
                        <li class="zm-collection-item zm-avatar">
                            <i class="zm-material-icons zm-circle zm-red zm">play_arrow</i>
                            <span class="zm-title zm">Title</span>
                            <p>First Line <br>
                                Second Line
                            </p>
                            <a href="#!" class="zm-secondary-content zm"><i class="zm-material-icons zm">grade</i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>