<html>
<head>
    <meta charset="UTF-8">
    <title>Footer</title>
    <?php include './include/head.html'?>
</head>
<body>
<div class="zm-container zm" style="position: relative; top: 20px;">
    <div class="zm-row">
        <div class="zm-col zm-s12 zm-m9 zm-l10">
            <div class="zm-row">
                <div class="zm-col zm-s12 zm-m12">
                    <footer class="zm-page-footer zm">
                        <div class="zm-container">
                            <div class="zm-row">
                                <div class="zm-col zm-l6 zm-s12">
                                    <h5 class="zm-white-text">Footer Content</h5>
                                    <p class="zm-grey-text zm-text-lighten-4">You can use rows and columns here to organize your footer content.</p>
                                </div>
                                <div class="zm-col zm-l4 zm-offset-l2 zm-s12">
                                    <h5 class="zm-white-text">Links</h5>
                                    <ul class="zm">
                                        <li><a class="zm-grey-text zm-text-lighten-3 zm" href="#!">Link 1</a></li>
                                        <li><a class="zm-grey-text zm-text-lighten-3 zm" href="#!">Link 2</a></li>
                                        <li><a class="zm-grey-text zm-text-lighten-3 zm" href="#!">Link 3</a></li>
                                        <li><a class="zm-grey-text zm-text-lighten-3 zm" href="#!">Link 4</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="zm-footer-copyright">
                            <div class="zm-container">
                                © 2014 Copyright Text
                                <a class="zm-grey-text zm-text-lighten-4 zm-right zm" href="#!">More Links</a>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>