<html>
<head>
    <meta charset="UTF-8">
    <title>Grid</title>
    <?php include './include/head.html'?>
</head>
<body>
<div style="width: auto; min-width: 100px; max-width: 700px; height: 500px; position: relative; margin: 50px auto; align-content: center">
    <div class="zm-row">
        <div class="zm-col zm-s1">1</div>
        <div class="zm-col zm-s1">2</div>
        <div class="zm-col zm-s1">3</div>
        <div class="zm-col zm-s1">4</div>
        <div class="zm-col zm-s1">5</div>
        <div class="zm-col zm-s1">6</div>
        <div class="zm-col zm-s1">7</div>
        <div class="zm-col zm-s1">8</div>
        <div class="zm-col zm-s1">9</div>
        <div class="zm-col zm-s1">10</div>
        <div class="zm-col zm-s1">11</div>
        <div class="zm-col zm-s1">12</div>
    </div>
</div>
</body>
</html>